# Generated by Django 4.2.4 on 2023-08-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mngaccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='copiedAccount',
            new_name='copied_at',
        ),
    ]
